[package]
name = "wlist_client_library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cipher = {version = "0.4.4", features=["block-padding"]}
rsa = "0.9.2"
aes = "0.8.2"
cbc = "0.1.2"
